version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0.0
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: circleci-demo-app
          deployment-group: circleci-demo-dg
          service-role-arn: arn:aws:iam::406974843324:role/CodeDeployTest-CodeDeployTrustRole-M1L4V1JZLN7F
          bundle-bucket: circleci-code-deploy-testing
          bundle-key: s3://circleci-code-deploy-testing/demo.zip
          arguments: '--profile assume_role'
